CREATE DATABASE IF NOT EXISTS task_management_system
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE task_management_system;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login DATETIME NULL DEFAULT NULL,
    login_count INT NOT NULL DEFAULT 0
);
